version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - meet-binder-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    restart: always

  postgres-gui:
    image: dpage/pgadmin4
    command: -s --bind=0.0.0.0 --listen=80 --url postgresql://db/postgres?user=root&password=root
    links:
      - db:db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 80:80
    restart: always

volumes:
  meet-binder-db:
